[bin]
target = "riscv64gc-unknown-linux-gnu" 

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-g++"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
